version: '3.8'
services:
  demo-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=demo
      - DEMO_MODE=true
    depends_on:
      - demo-db
    restart: unless-stopped
    
  demo-db:
    image: postgres:15
    environment:
      POSTGRES_DB: openpermit_demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo123
    volumes:
      - ./demo-data:/docker-entrypoint-initdb.d
    restart: unless-stopped
    
  demo-monitoring:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./demo/monitoring:/usr/share/nginx/html
    restart: unless-stopped
