name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage
      - name: Run Python tests with coverage
        run: |
          coverage run -m pytest
          coverage xml
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Run Node tests
        run: npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install ESLint
        run: npm install eslint
      - name: Run ESLint
        run: npx eslint .

  unit-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run unit tests with coverage
        run: NODE_V8_COVERAGE=coverage npm test
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          directory: coverage
          fail_ci_if_error: true
          flags: unittests

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v3
      - name: Integration tests
        run: echo "No integration tests defined"

  e2e-tests:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
